"""Add indexes to recipes and tags

Revision ID: cca4cdb1b240
Revises: 
Create Date: 2026-04-11 17:11:03.084094

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cca4cdb1b240'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recipes_cooking_time'), ['cooking_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_recipes_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_recipes_difficulty'), ['difficulty'], unique=False)
        batch_op.create_index(batch_op.f('ix_recipes_prep_time'), ['prep_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_recipes_title'), ['title'], unique=False)

    with op.batch_alter_table('tags', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tags_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_tags_tag_type'), ['tag_type'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tags', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tags_tag_type'))
        batch_op.drop_index(batch_op.f('ix_tags_name'))

    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recipes_title'))
        batch_op.drop_index(batch_op.f('ix_recipes_prep_time'))
        batch_op.drop_index(batch_op.f('ix_recipes_difficulty'))
        batch_op.drop_index(batch_op.f('ix_recipes_created_at'))
        batch_op.drop_index(batch_op.f('ix_recipes_cooking_time'))

    # ### end Alembic commands ###
